# Creates pull requests to keep dependencies secure and up-to-date.
version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
