# Generated by Django 3.0.11 on 2020-12-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=200, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "nutriscore_grade",
                    models.CharField(max_length=300, verbose_name="Nutriscode Grade"),
                ),
                ("url", models.URLField(help_text="Url to the openfoodfacts website")),
                ("image_url", models.URLField(blank=True)),
                ("categories", models.ManyToManyField(to="products.Category")),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
    ]
