# Generated by Django 3.0.11 on 2020-12-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(max_length=200, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
    ]
