# Generated by Django 3.0.11 on 2021-01-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.CharField(
                default="none", max_length=200, verbose_name="Category"
            ),
        ),
    ]
