# Generated by Django 3.0.11 on 2020-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20201231_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="nutriscore_grade",
            field=models.CharField(max_length=300, verbose_name="Nutriscode Grade"),
        ),
    ]
