# Generated by Django 3.0.11 on 2021-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210105_1729"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="products.Category"),
        ),
    ]
