# Generated by Django 3.1.2 on 2021-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20210105_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="products.Category"
            ),
        ),
    ]
