# Generated by Django 3.1.2 on 2021-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20210107_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_nutrition_url",
            field=models.URLField(blank=True),
        ),
    ]
