language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements/local.txt

env: DJANGO_SETTINGS_MODULE="frontdesk.config.test"

services:
  - postgresql

script:
  - ./manage.py pytest