
name: CI

on: [push]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  py39:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 'postgres'
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run tests 
      env:
        POSTGRES_DB: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      run: |
        pytest