language: python
python:
  - '3.5'

on: [push]


before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=config.settings.test

script:
  - ./manage.py pytest